language: cpp
dist: bionic
sudo: required

cache:
  directories:
    - $HOME/.conan/data

branches:
  only:
    - develop
    - master

compiler:
  - gcc

before_install:
  - sudo apt-get install -y doxygen lcov python3 python3-pip python3-setuptools
  - sudo rm /usr/bin/python
  - sudo ln -s /usr/bin/python3 /usr/bin/python
  - pip3 install --user cpp-coveralls conan

install:
  # Create folder to store dependencies
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR}
  # Upgrade CMake
  - cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.15/cmake-3.15.5-Linux-x86_64.tar.gz
  - echo "473e73f3858496c9a64c73666ee7d5f5  cmake-3.15.5-Linux-x86_64.tar.gz" > cmake_md5.txt
  - md5sum -c cmake_md5.txt
  - tar -xf cmake-3.15.5-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.15.5-Linux-x86_64 cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cmake -version
  - cd ${TRAVIS_BUILD_DIR}
  # Install lcov to coveralls conversion + upload tool
  - gem install coveralls-lcov
  # Install dependencies using Conan
  - conan profile new --detect default
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan install -if build . --build=missing

script:
  - cmake -Bbuild -DENABLE_COVERAGE=YES .
  - cmake --build build/ --target build_tests
  - cmake --build build/ --target test
  - cmake --build build/ --target coverage

after_success:
  - lcov --list coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} build/test-report/coverage.info
