language: cpp
dist: bionic
sudo: required

branches:
  only:
    - develop
    - master

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls

install:
  - sudo apt-get install -y doxygen lcov
  # Create folder to store dependencies
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR}
  # Upgrade CMake
  - cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.15/cmake-3.15.5-Linux-x86_64.tar.gz
  - echo "473e73f3858496c9a64c73666ee7d5f5  cmake-3.15.5-Linux-x86_64.tar.gz" > cmake_md5.txt
  - md5sum -c cmake_md5.txt
  - tar -xf cmake-3.15.5-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.15.5-Linux-x86_64 cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cmake -version
  - cd ${TRAVIS_BUILD_DIR}
  # Install lcov to coveralls conversion + upload tool
  - gem install coveralls-lcov

script:
  - cmake -Bbuild -DENABLE_COVERAGE=YES .
  - cmake --build build/ --target build_tests
  - cmake --build build/ --target test
  - cmake --build build/ --target coverage

after_success:
  - lcov --list coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} build/test-report/coverage.info
